### ISSUE TITLE
UTC time with am/pm is confusing

### ISSUE THREAD

**Issue by donpdonp** [achow101/forkmon#18]
Having AM/PM implies an association with a country that uses AM/PM, so its confusing. The norm for reporting UTC time is to use 24-hour time.

**Comment by code-runner-77** [comment]
"AM" and "PM" should not be on the site.  **UTC** with 24 hr (or military) time format should be exclusively used to avoid confusion. 

Also this wording is confusing and ambiguous for each node: 

**Has not forked but is behind other nodes?**:  Yes

It is answered "Yes" for Bitcoin Cash... Bitcoin Cash has forked from Bitcoin but has not forked itself and yes it is currently behind other nodes.  Hopefully this .info can add accurate information and not add to the widespread confusion with wordings like this....

How about breaking this into two questions:

Has this chain forked? Yes or No
It is currently behind other Nodes?  Yes or No

Lastly the **Blue** border color on Bitcoin cash is not explained - all others are **green** - with no description on green either.

**Comment by achow101** [comment]
Pull requests welcome

**Comment by achow101** [comment]
Done in 6de1a2e324e63449ec47461ffef67c1f126f81ed. This will go on the website later along with other changes.
