### ISSUE TITLE
Doesn't seem to work

### ISSUE THREAD

**Issue by HouzuoGuo** [achow101/forkmon#19]
Hey there!

It's been nearly 12 hours since first cash block was mined, your website still doesn't see fork happening.

**Comment by achow101** [comment]
That is expected behavior. The site will not warn for a chain split for planned hard forks like the bitcoin cash fork. Sufficient warning is given by showing the node as blue and the blocks at the fork height.

**Comment by HouzuoGuo** [comment]
Oh, thanks!
