### ISSUE TITLE
BCH is current "Yes" for "Has not forked but is behind other nodes"

### ISSUE THREAD

**Issue by warwickchapman** [achow101/forkmon#21]
Surely, that should be no?

It has forked.

I recall at one point after the first block was mined this turned to "No".

**Comment by code-runner-77** [comment]
Agree completely.  I opened it as a separate **Issue** separately as Confusing / Ambiguous working - break it into two questions

**Comment by achow101** [comment]
Pull requests welcome

**Comment by achow101** [comment]
I have changed this to just indicate whether the node is behind in 011855bee49293160f2f7f90985104074962c7ea. Fork status is shown by the coloration of the cards.
