### ISSUE TITLE
Very confusing / ambiguous wording: Has not forked but is behind other nodes? 

### ISSUE THREAD

**Issue by code-runner-77** [achow101/forkmon#22]
Also this wording is confusing and ambiguous for each node:

Has not forked but is behind other nodes?: Yes

It is answered "Yes" for Bitcoin Cash... Bitcoin Cash has forked from Bitcoin but has not forked itself and yes it is currently behind other nodes. Hopefully this .info can add accurate information and not add to the widespread confusion with wordings like this....

How about breaking this into two questions:
Has it forked for other nodes?   Yes or NO
Is it behind other nodes?  Yes or No

**Comment by achow101** [comment]
Pull requests welcome

**Comment by achow101** [comment]
I have changed this to just indicate whether the node is behind in 011855bee49293160f2f7f90985104074962c7ea. Fork status is shown by the coloration of the cards.

**Comment by code-runner-77** [comment]
Sounds much better.
