### ISSUE TITLE
Phantom chain split detected

### ISSUE THREAD

**Issue by bendelo** [achow101/forkmon#9]
btcforkmonitor.info currently says:
>WARNING: A CHAIN SPLIT WAS DETECTED BUT HAS BEEN RE-ORGED.

However all 5 nodes also say 
>Has Experienced a Blockchain Reorganization: No

**Comment by achow101** [comment]
I will look into what caused that. It does not look like there were any chain splits (all of my nodes agree with each other with their chaintips) so I have reset the site to not show the warning. I believe this may just be a problem with latency and concurrent database operations.

**Comment by feriancek** [comment]
Could it be related to the invalid blocks that were mined?
https://bitcointalk.org/index.php?topic=2041607.0

**Comment by achow101** [comment]
The invalid blocks are unrelated.
